#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# Add icons of general interest
#
/control/execute icons.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run run "/control/execute run.mac"
/gui/addButton run Na22SolidAng "/control/execute Na22SolidAng.mac"
/gui/addButton run Na22Decay "/control/execute Na22Decay.mac"
/gui/addButton run Xray60keV "/control/execute Xray_60keV.mac"
/gui/addButton run 511keV "/control/execute 511keV.mac"

#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "50 MeV"  "/gun/energy 50 MeV"
/gui/addButton gun "1 GeV"   "/gun/energy 1 GeV"
/gui/addButton gun "10 GeV"  "/gun/energy 10 GeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
#
# Vis menu :
/gui/addMenu vis Vis
/gui/addButton vis DAWNFILE  "/control/execute dawnFile.mac"
/gui/addButton vis OpenInventor "/control/execute visTutor/exN03Vis5.mac"
/gui/addButton vis TimeSlicing "/control/execute visTutor/exN03Vis12.mac"
/gui/addButton vis EmShower "/control/execute visTutor/exN03Vis13.mac"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wireframe"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
/gui/addButton viewer "View point: -90 0" "/vis/viewer/set/viewpointThetaPhi -90. 0."
/gui/addButton viewer "View point: 45 45" "/vis/viewer/set/viewpointThetaPhi 45. 45."
/gui/addButton viewer "View point: 45 90" "/vis/viewer/set/viewpointThetaPhi 45. 90."
/gui/addButton viewer "View point: 0 90" "/vis/viewer/set/viewpointThetaPhi 0. 90."
/gui/addButton viewer "View point: 180 0" "/vis/viewer/set/viewpointThetaPhi 180. 0."
#
# To limit the output flow in the "dump" widget :
/run/printProgress 100
#
# User defined icon :
/gui/addIcon "Run beam on" user_icon "/control/execute Na22SolidAng.mac" run.png 
/gui/addIcon "Run 511keV" user_icon "/control/execute 511keV.mac" list.png 
